FROM ubuntu:24.04

LABEL maintainer="ezio.melotti@gmail.com"

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    python3-venv \
    python3-dev \
    build-essential \
    curl && \
    rm -rf /var/lib/apt/lists/*

# Create and activate a virtual environment
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN pip install --upgrade pip wheel

COPY ./requirements.txt /simoc/requirements.txt
RUN pip install -r /simoc/requirements.txt

COPY . /simoc

# Create a non-root user and set permissions
RUN groupadd -r simoc && \
    useradd --no-log-init -r -g simoc -s /bin/bash simoc && \
    chown -R simoc:simoc /simoc /opt/venv

ARG DB_TYPE
ARG DB_HOST
ARG DB_PORT
ARG DB_NAME
ARG DB_USER
ARG DB_PASSWORD
ARG REDIS_HOST
ARG REDIS_PORT
ARG REDIS_PASSWORD

ENV DB_TYPE ${DB_TYPE}
ENV DB_HOST ${DB_HOST}
ENV DB_PORT ${DB_PORT}
ENV DB_NAME ${DB_NAME}
ENV DB_USER ${DB_USER}
ENV DB_PASSWORD ${DB_PASSWORD}
ENV REDIS_HOST ${REDIS_HOST}
ENV REDIS_PORT ${REDIS_PORT}
ENV REDIS_PASSWORD ${REDIS_PASSWORD}

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

USER simoc
WORKDIR /simoc

ENTRYPOINT [ "/bin/bash" ]
CMD ["start_worker.sh"]
